### ISSUE TITLE
Crash on refresh from widget

### ISSUE THREAD

**Issue by aimilushev** [mrgames13/Feinstaub-App#12]
After the latest update the app crashes everytime you try to refresh the data from the home screen widget

**Comment by 5t0rmr1d3r** [comment]
@aimilushev confirmed, here the same,
i thought on my phone the reason is, that i have no gapps/gms installed.

**Comment by mrgames13** [comment]
Ok. We're going to look after that.

**Comment by mrgames13** [comment]
This should be fixed. The changings will be applied in the next update.

**Comment by shellmann** [comment]
For me it is still not fixed.
Android 9.
App version 3.1.1

**Comment by mrgames13** [comment]
Ok. We just fixed that issue. The patch will be included in version 3.2.1. Thanks for reporting that!
