### ISSUE TITLE
Diagram scaling with air pressure sensor

### ISSUE THREAD

**Issue by PYCODR** [mrgames13/feinstaub-app#25]
If a sensor supports air pressure measurement(like BME-280) and sends those measure points to the database, the curves for pressure, temp and humidity share a scale from 0 to 1000. This results in a diagram with no useful information:
- temp and humidity are scaled to 0..1000, just a line at the bottom with no visible changes
- air pressure is scaled to 0..1000, just a line at the top with no visible changes
![Screenshot_20190702-090940_Particulate Matter App](https://user-images.githubusercontent.com/52443105/60491765-ce88f900-9ca9-11e9-92c1-9f3e6050eb8e.jpg)
![Screenshot_20190702-091504_Particulate Matter App](https://user-images.githubusercontent.com/52443105/60491942-2e7f9f80-9caa-11e9-8f43-e1f07f8dbedb.jpg)

**Comment by mrgames13** [comment]
This issue is fixed in the latest beta. Will be released in the next few days.
