### ISSUE TITLE
Feature request: monitoring widget

### ISSUE THREAD

**Issue by aimilushev** [mrgames13/Feinstaub-App#5]
I love the app! One feature I miss is observing my sensor's data in the home screen of my phone with an android widget. Currently I have another app "Asia air quality" that has such widget. It's not tied to my sensor, but to a official public one. I hope you like the idea.

**Comment by mrgames13** [comment]
Hello,
we like the idea and we already heared it a few times. Now we're going to implement this into our app, but it can last a few weeks. Thanks for your feature request.

**Comment by mrgames13** [comment]
We added this feature (https://github.com/mrgames13/Feinstaub-App/commit/205db5494cbcf20581e5e18535ee33695dab6265). We will test it and release the update the next few days.

**Comment by aimilushev** [comment]
You are awesome !!!
