### ISSUE TITLE
Add numeric scale and unit on diagram

### ISSUE THREAD

**Issue by lodagro** [mrgames13/Feinstaub-App#7]
Would it be possible to add a numeric scale and unit on the diagram?

**Comment by mrgames13** [comment]
We will attach an unit to the graphs. What do you mean with numeric scale?

**Comment by mrgames13** [comment]
We already have something like that. You can tap on the graph to open it in fullscreen mode. There are axis labels enabled. See attached screenshot (https://goo.gl/aVBhyp).

**Comment by lodagro** [comment]
Ok, so no plans to add this also on the non-fullscreen graph? Text will probably be too small i guess.
Thanks for adding units on the fullscreen graph.

**Comment by mrgames13** [comment]
There is not enough space for it. There are phones with 2.7 inches out there. Indeed thanks for reporting this issue. We would be happy, if you give us a good review on Google Play.

**Comment by vikin91** [comment]
I think adding numbers to axes is important - without numbers the chars shows only changes of a value, whereas for air pollution the absolute value is the one that people should be interested in.

I am sure you can find some place to squeeze in these numbers, don't give up!
